import SectionImage from '../components/SectionImage'
import {site} from '../config/site'
export default function About(){return <main>
 <AboutRow image="about-image.jpg" title={`About ${site.displayName}`} number="No:1" label={<>In<br/>Serving you</>}><p>{site.displayName} is built around a commitment to serving fresh and delectable dishes. We've carefully curated a menu that reflects our passion for culinary excellence. Whether you're seeking the comfort of traditional flavors or the excitement of modern cuisine, {site.displayName} is your trusted partner in the world of food.</p><p>We offer a comprehensive range of services designed to elevate your dining experience, from food and table booking to events and catering.</p></AboutRow>
 <AboutRow reverse image="about2.png" title="Mission Statement" number="YES" label={<>WE<br/>have a goal</>}><p>Our mission is simple yet profound: to create memorable food experiences that touch the heart. We aim to elevate your dining adventures, ensuring that every meal you enjoy with us leaves a lasting impression.</p><p>We also understand the importance of food for everyone in our society and support food donation programmes to help those in need.</p></AboutRow>
 <AboutRow image="about3.png" title="History"><p>{site.displayName} was founded by food enthusiasts and a seasoned chef with a vision to redefine dining experiences. Since our establishment, we've embarked on a journey of culinary exploration, continuously striving for excellence.</p><p>The company was born out of a desire to transform ordinary meals into extraordinary experiences and make every meal special, regardless of the occasion.</p></AboutRow>
 <AboutRow reverse image="about4.png" title="Features and Services"><p><b>Food Delivery:</b> Efficient food delivery brings restaurant-quality meals to your doorstep.<br/><br/><b>Table Booking:</b> Reserve your preferred table for a seamless dining experience.<br/><br/><b>Event Catering:</b> Our catering services are designed to delight your guests.<br/><br/><b>Premium Membership:</b> Enjoy exclusive discounts and promotions.<br/><br/><b>Menu Display:</b> Explore our diverse menu offerings.<br/><br/><b>Feedback Section:</b> Your feedback helps us improve.</p></AboutRow>
 <section className="grid grid-cols-1 gap-[60px] px-[30px] py-[60px] lg:grid-cols-[3fr_4fr] lg:items-center lg:gap-[80px] lg:py-[100px]"><SectionImage src={site.ceoImage}/><div><h2 className="section-title mb-[30px]">Meet our CEO</h2><p className="mb-2 text-xl font-semibold text-cadet">{site.ceo}</p><p className="mb-[30px] text-[15px] font-medium text-saffron">{site.ceoTitle}</p><p className="section-text max-w-none">The CEO profile image is intentionally kept as a replaceable asset. Replace <b>public/assets/images/ceo.jpg</b> with the real photo and the UI will update automatically.</p></div></section>
 </main>}
function AboutRow({reverse,image,title,number,label,children}){return <><section className={`grid grid-cols-1 gap-[60px] px-[30px] py-[60px] lg:grid-cols-[3fr_4fr] lg:items-center lg:gap-[80px] lg:py-[100px] ${reverse?'lg:[&>div:first-child]:order-2':''}`}><SectionImage src={`/assets/images/${image}`} number={number} label={label}/><div><h2 className="section-title mb-[30px]">{title}</h2>{children}</div></section><hr className="mx-[30px] border-cultured"/></>}
