import SectionImage from '../components/SectionImage'
import { site } from '../config/site'

export default function About(){return <main>
 <AboutRow image="about-image.jpg" title={`About ${site.displayName}`} number="01" label={<>Private<br/>experiences</>}><p>{site.displayName} is a private-service business connecting clients with culinary professionals and selected services for celebrations, gatherings, travel, and everyday needs.</p><p>Our website is organized by department so clients can see what is currently confirmed and contact the team directly for availability and details.</p></AboutRow>
 <AboutRow reverse image="about2.png" title="Our approach" number="02" label={<>Direct<br/>contact</>}><p>For services that already have confirmed professionals, their profiles are shown on the Professionals page.</p><p>For departments still being prepared, we intentionally show that information is coming soon instead of publishing unconfirmed details.</p></AboutRow>
 <AboutRow image="about3.png" title="Departments" number="03"><p>Current departments include private chefs, DJs, service, apartments for rent, private cars for rent, buffet setup, tour guiders, private drivers, and house keeping.</p><p>New professionals, photos, videos, and service details can be added as they are confirmed.</p></AboutRow>
 <AboutRow reverse image="about4.png" title="Talk to the CEO" number="04"><p><b>CEO:</b> {site.ceo} ({site.ceoTitle})</p><p>For bookings, availability, partnerships, or questions about a department, use the WhatsApp contact on this website or call {site.phoneDisplay}.</p><a href={`https://wa.me/${site.whatsapp}`} target="_blank" rel="noreferrer" className="brand-btn brand-btn-primary mt-5">WhatsApp the CEO</a></AboutRow>
 <section className="grid grid-cols-1 gap-[60px] px-[30px] py-[60px] lg:grid-cols-[3fr_4fr] lg:items-center lg:gap-[80px] lg:py-[100px]"><SectionImage src={site.ceoImage}/><div><h2 className="section-title mb-[30px]">Meet our CEO</h2><p className="mb-2 text-xl font-semibold text-cadet">{site.ceo}</p><p className="mb-[30px] text-[15px] font-medium text-saffron">{site.ceoTitle}</p><a href={`https://wa.me/${site.whatsapp}`} target="_blank" rel="noreferrer" className="brand-btn brand-btn-primary">Contact the CEO</a></div></section>
 </main>}
function AboutRow({reverse,image,title,number,label,children}){return <><section className={`grid grid-cols-1 gap-[60px] px-[30px] py-[60px] lg:grid-cols-[3fr_4fr] lg:items-center lg:gap-[80px] lg:py-[100px] ${reverse?'lg:[&>div:first-child]:order-2':''}`}><SectionImage src={`/assets/images/${image}`} number={number} label={label}/><div><h2 className="section-title mb-[30px]">{title}</h2><div className="space-y-5 leading-7 text-rhythm">{children}</div></div></section><hr className="mx-[30px] border-cultured"/></>}
