import { Link } from 'react-router-dom'
import DecorativeFood from '../components/DecorativeFood'
import { site } from '../config/site'

const services=[['01','Online food delivery','You can order the foods from our restaurant online and we will deliver in your doorsteps, you can also track the progress of delivery.'],['02','Table booking','You can pre-book a table available in our restaurant, that desired table will be free for you when you come.'],['03','Bulk booking & catering for events','Our restaurant offers catering service and you can book bulk food for events like wedding.'],['04','Discount for premium members','If you are a premium member in our website, you will get special discount from our restaurant.'],['05','Food Donation','As food enthusiasts we know the importance and value of food for everyone in our society. We donate food for the needed ones.']]
const dishes=[['menu1.jpg','Special Biriyani','180'],['menu2.jpg','Chicken Al Fahm','720'],['menu3.jpg','Veg Salad','120','Vegan'],['menu4.jpg','Ramen','400','Hot'],['menu5.jpg','Veg Pasta','100','Vegan'],['menu6.jpg','Chappathi','80']]
export default function Home(){return <main>
<section className="grid grid-cols-1 items-center gap-[50px] px-[30px] pb-[60px] pt-[150px] lg:grid-cols-2 lg:py-[100px] lg:pt-[150px]">
 <div className="text-center lg:text-left"><p className="mb-[30px] inline-block bg-cultured p-1 text-[13px]">Hi, new friend !</p><h1 className="mb-[30px] text-[46px] font-semibold leading-[1.1] tracking-[-2px] text-cadet sm:text-[54px] md:text-[72px]">We do not cook, we create your emotions!</h1><p className="mx-auto mb-[30px] max-w-[320px] leading-[1.6] text-rhythm lg:mx-0">Your tongue also have it's own dreams. {site.displayName} is the perfect place for your fantasies.</p><div className="flex flex-col items-center gap-[15px] sm:flex-row sm:justify-center lg:justify-start"><Link to="/login" className="brand-btn brand-btn-primary"><img src="/assets/images/menu.svg" alt=""/>Login</Link><Link to="/about" className="brand-btn brand-btn-secondary"><img src="/assets/images/arrow.svg" alt=""/>About us</Link></div></div>
 <DecorativeFood />
</section>
<section className="grid grid-cols-1 gap-[60px] px-[30px] py-[60px] lg:grid-cols-[3fr_4fr] lg:items-center lg:gap-[80px] lg:py-[100px]">
 <div className="relative"><div className="aspect-square overflow-hidden md:aspect-[5/3] lg:aspect-auto"><img src="/assets/images/about-image.jpg" alt="" className="h-full w-full object-cover animate-lazyScaleUp"/></div><div className="absolute -bottom-5 -right-5 bg-white p-[30px] text-center shadow-card"><div className="border-[3px] border-dotted border-cultured p-2.5"><p className="font-monoton text-[46px] text-cadet">1</p><p className="text-lg font-semibold text-cadet">In<br/>Serving you</p></div></div></div>
 <div><h2 className="section-title mb-[30px]">We are doing more than you expect</h2><p className="section-text mb-[30px] max-w-none">At {site.displayName}, we are more than just a food hub - we're your culinary companions on a delightful journey through flavors, tastes, and experiences. Our passion for food, combined with a commitment to quality and innovation, drives everything we do.<br/><br/>We believe in the magic of fresh ingredients, thoughtfully prepared recipes, and the joy of sharing a meal with loved ones.</p><p className="section-text max-w-none">We offer a comprehensive range of services designed to elevate your dining experience, from delicious food and special events to table booking and catering.</p><img src="/assets/images/signature.png" alt="signature" width="150" className="mt-5"/></div>
</section>
<section className="grid grid-cols-1 gap-10 px-[30px] py-[60px] md:grid-cols-2 lg:grid-cols-3 lg:gap-x-[30px] lg:gap-y-[60px]">{services.map(([n,t,d])=><div key={n} className="md:grid md:grid-cols-[auto_1fr] md:gap-x-[30px]"><p className="font-monoton text-[42px] leading-none text-saffron md:row-span-2">{n}</p><h3 className="mb-5 text-lg font-semibold tracking-[-1px] text-cadet">{t}</h3><p className="text-[15px] leading-[1.5] text-rhythm">{d}</p></div>)}</section>
<div className="pb-[60px] text-center"><Link to="/services" className="brand-btn brand-btn-secondary"><img src="/assets/images/arrow.svg" alt=""/>Explore our services</Link></div>
<section className="px-[30px] py-[60px]"><h2 className="section-title mb-[30px]">Most popular dishes</h2><p className="section-text mb-[60px]">The following dishes have a high demand in our restaurant😁</p><div className="mb-[50px] grid grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-3 lg:gap-x-10 lg:gap-y-[60px]">{dishes.map(([img,name,price,badge])=><div key={name} className="group"><div className="relative overflow-hidden"><img src={`/assets/images/${img}`} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>{badge&&<span className={`absolute left-[15px] top-[15px] px-2 py-1 text-sm ${badge==='Vegan'?'bg-pistachio':'bg-crayola'}`}>{badge}</span>}</div><div className="flex items-center justify-between bg-cultured"><h3 className="px-[15px] text-lg font-semibold text-cadet">{name}</h3><p className="flex h-[60px] w-[60px] items-center justify-center bg-saffron text-2xl font-medium text-cadet"><span className="text-xs">₹</span>{price}</p></div><p className="py-[15px] text-[15px] leading-[1.6] tracking-[.4px] text-rhythm">tomatoes, nori, feta cheese, mushrooms, rice noodles, corn, shrimp.</p><div className="flex gap-1 text-saffron">★★★★★</div></div>)}</div><Link to="/menu" className="brand-btn brand-btn-primary"><img src="/assets/images/menu.svg" alt=""/>Full menu</Link></section>
<section className="px-[30px] pb-[120px] pt-[60px] lg:pb-[200px]"><h2 className="section-title mb-[15px]">What our customers say?</h2><p className="section-text mb-[50px]">Consectetur numquam poro nemo veniam eligendi rem adipisci quo modi.</p><div className="grid grid-cols-1 gap-[50px] md:grid-cols-2"><Testimonial title="Very tasty" image="testimonials1.jpg" name="Emma Newman"/><Testimonial title="I have lunch here every day" image="testimonials2.jpg" name="Robert William"/></div></section>
</main>}
function Testimonial({title,image,name}){return <div><h4 className="mb-[15px] font-semibold text-cadet">{title}</h4><div className="mb-[15px] flex gap-1 text-saffron">★★★★★</div><p className="mb-[15px] text-[15px] leading-[1.4] tracking-[.5px] text-rhythm">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis fugiat totam nobis quas unde excepturi inventore possimus laudantium provident.</p><div className="flex items-center gap-[15px]"><div className="h-[50px] w-[50px] overflow-hidden rounded-full"><img src={`/assets/images/${image}`} alt="" className="h-full w-full object-cover"/></div><h5 className="text-sm font-semibold text-cadet">{name}</h5></div></div>}
